apiVersion: apps/v1
kind: Deployment
metadata:
  name: uself-agent
  namespace: retail
  labels:
    app: uself-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uself-agent
  template:
    metadata:
      labels:
        app: uself-agent
    spec:
      imagePullSecrets:
      - name: retail
      containers:
      - name: uself-agent
        image: harbor.tango.rid-intrasoft.eu/eviden/rd/uself/uself-agent:v0.4.12.2
        imagePullPolicy: Always
        env: 
        - name: LETSENCRYPT_HOST
          value: uself-agent-tango.metro.com.gr
        - name: VIRTUAL_HOST
          value: uself-agent-tango.metro.com.gr
        - name: VIRTUAL_PORT
          value: "8888"
        - name: spring_data_redis_host
          value: "redis-uself-agent" #redis-uself-agent.ips-testing1.svc.cluster.local          # uself-redis-local
        - name: uself_did_method
          value: DID_KEY_P256
        - name: uself_preload
          value: tango
        - name: uself_loadDir
          value: "/app/data/tango-data.json"
        - name: uself_server
          value: https://uself-agent-tango.metro.com.gr
        ports:
        - containerPort: 8888
