apiVersion: apps/v1
kind: Deployment
metadata:
  name: uself-agent
  namespace: smart-hospitality
  labels:
    app: uself-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uself-agent
  template:
    metadata:
      labels:
        app: uself-agent
    spec:
      imagePullSecrets:
      - name: regcred-prod
      containers:
      - name: uself-agent
        image: harbor.tango.rid-intrasoft.eu/eviden/rd/uself/uself-agent:v0.4.9
        imagePullPolicy: Always
        env: 
        - name: LETSENCRYPT_HOST
          value: uself-agent.tango.nadiaplatform.com
        - name: VIRTUAL_HOST
          value: uself-agent.tango.nadiaplatform.com
        - name: VIRTUAL_PORT
          value: "8888"
        - name: spring_data_redis_host
          value: "redis-uself-agent" 
        - name: uself_did_method
          value: DID_KEY_P256
        - name: uself_preload
          value: tango
        - name: uself_server
          value: https://uself-agent.tango.nadiaplatform.com
        ports:
        - containerPort: 8888
