apiVersion: v1
kind: Service 
metadata:
  name: uself-agent-service
  namespace: smart-manufacturing
  labels:
    app: uself-agent
spec:
  selector:
    app: uself-agent
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
