apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    components: uself-agent
  name: uself-agent-service-ingress
  namespace: ips-testing1
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - uself-agent.k8s-cluster.tango.rid-intrasoft.eu
    secretName: uself-agent-cert-tls
  rules:
  - host: uself-agent.k8s-cluster.tango.rid-intrasoft.eu
    http:
      paths:
      - backend:
          service:
            name: uself-agent-service
            port:
              number: 8888
        path: /
        pathType: Prefix
