apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    #components: uself-agent
    app: uself-agent
  name: uself-agent-service-ingress
  namespace: retail
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k     #Added in NGINX buffer increases
    nginx.ingress.kubernetes.io/client-header-buffer-size: 256k
    nginx.ingress.kubernetes.io/http2-max-header-size: 96k
    nginx.ingress.kubernetes.io/large-client-header-buffers: 4 256k
    nginx.ingress.kubernetes.io/load-balance: ewma
    nginx.ingress.kubernetes.io/proxy-body-size: 150m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1000"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1000"
    nginx.ingress.kubernetes.io/server-snippet: | # this is where the magic happens
      client_header_buffer_size 100k;
      large_client_header_buffers 4 256k;
      connection_pool_size 256k;
      proxy_buffer_size 128k;
      proxy_buffers 8 256k;
      proxy_busy_buffers_size 256k;
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "*.metro.com.gr"
    secretName: metroingress
  rules:
  - host: uself-agent-tango.metro.com.gr
    http:
      paths:
      - backend:
          service:
            name: uself-agent-service
            port:
              number: 8888
        path: /
        pathType: Prefix
